// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://gukruwlvavtzwpjywggj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd1a3J1d2x2YXZ0endwanl3Z2dqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4Nzc4ODksImV4cCI6MjA2NDQ1Mzg4OX0.B_j9ZpAiTyrbsRanSygS_LpEmxLpVo1uwaqrkDDgo80";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      storage: localStorage,
      autoRefreshToken: true,
      detectSessionInUrl: true,
    },
  }
);
